"""initial schema

Revision ID: 7e5e7da2ccb9
Revises: 
Create Date: 2026-07-22 04:59:11.003799
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7e5e7da2ccb9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benchmarks',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('mfapi_scheme_code', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_benchmarks')),
    sa.UniqueConstraint('name', name=op.f('uq_benchmarks_name'))
    )
    op.create_table('companies',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('revenue_cr', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('ebitda_cr', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('promoter_holding_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies'))
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_sector'), ['sector'], unique=False)

    op.create_table('roles',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_name'), ['name'], unique=True)

    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_users_role_id_roles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role_id'), ['role_id'], unique=False)

    op.create_table('clients',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('risk_profile', sa.String(length=30), nullable=True),
    sa.Column('relationship_manager_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['relationship_manager_id'], ['users.id'], name=op.f('fk_clients_relationship_manager_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clients'))
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clients_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_clients_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_relationship_manager_id'), ['relationship_manager_id'], unique=False)

    op.create_table('deals',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('client_id', sa.Uuid(), nullable=True),
    sa.Column('stage', sa.String(length=30), nullable=False),
    sa.Column('deal_type', sa.String(length=50), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('size_cr', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('probability_pct', sa.Integer(), nullable=True),
    sa.Column('next_action', sa.String(length=255), nullable=True),
    sa.Column('next_action_date', sa.Date(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_deals_client_id_clients'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_deals_company_id_companies'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_deals_owner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deals'))
    )
    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deals_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deals_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deals_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_deals_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deals_stage'), ['stage'], unique=False)

    op.create_table('portfolios',
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('inception_date', sa.Date(), nullable=True),
    sa.Column('benchmark_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['benchmark_id'], ['benchmarks.id'], name=op.f('fk_portfolios_benchmark_id_benchmarks')),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_portfolios_client_id_clients'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolios'))
    )
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolios_benchmark_id'), ['benchmark_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolios_client_id'), ['client_id'], unique=False)

    op.create_table('activities',
    sa.Column('deal_id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('activity_type', sa.String(length=30), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_activities_actor_id_users')),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], name=op.f('fk_activities_deal_id_deals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activities'))
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activities_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activities_deal_id'), ['deal_id'], unique=False)

    op.create_table('ai_reports',
    sa.Column('deal_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('output_md', sa.Text(), nullable=True),
    sa.Column('edited_md', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_ai_reports_created_by_id_users')),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], name=op.f('fk_ai_reports_deal_id_deals'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_reports'))
    )
    with op.batch_alter_table('ai_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_reports_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_reports_deal_id'), ['deal_id'], unique=False)

    op.create_table('holdings',
    sa.Column('portfolio_id', sa.Uuid(), nullable=False),
    sa.Column('instrument_type', sa.String(length=20), nullable=False),
    sa.Column('identifier', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('units', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('avg_cost', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('asset_class', sa.String(length=20), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('geography', sa.String(length=100), nullable=True),
    sa.Column('price_source', sa.String(length=20), nullable=False),
    sa.Column('manual_price', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('manual_price_date', sa.Date(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_holdings_portfolio_id_portfolios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_holdings'))
    )
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_holdings_identifier'), ['identifier'], unique=False)
        batch_op.create_index(batch_op.f('ix_holdings_portfolio_id'), ['portfolio_id'], unique=False)

    op.create_table('notes',
    sa.Column('deal_id', sa.Uuid(), nullable=True),
    sa.Column('client_id', sa.Uuid(), nullable=True),
    sa.Column('author_id', sa.Uuid(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_notes_author_id_users')),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_notes_client_id_clients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], name=op.f('fk_notes_deal_id_deals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notes'))
    )
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notes_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notes_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notes_deal_id'), ['deal_id'], unique=False)

    op.create_table('reports',
    sa.Column('portfolio_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('generated_by_id', sa.Uuid(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['generated_by_id'], ['users.id'], name=op.f('fk_reports_generated_by_id_users')),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_reports_portfolio_id_portfolios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_generated_by_id'), ['generated_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_portfolio_id'), ['portfolio_id'], unique=False)

    op.create_table('tasks',
    sa.Column('deal_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('assignee_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], name=op.f('fk_tasks_assignee_id_users')),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], name=op.f('fk_tasks_deal_id_deals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_assignee_id'), ['assignee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_deal_id'), ['deal_id'], unique=False)

    op.create_table('uploaded_files',
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('stored_path', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('portfolio_id', sa.Uuid(), nullable=True),
    sa.Column('uploaded_by_id', sa.Uuid(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('error_report', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_uploaded_files_portfolio_id_portfolios'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], name=op.f('fk_uploaded_files_uploaded_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uploaded_files'))
    )
    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_uploaded_files_portfolio_id'), ['portfolio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_uploaded_files_uploaded_by_id'), ['uploaded_by_id'], unique=False)

    op.create_table('transactions',
    sa.Column('portfolio_id', sa.Uuid(), nullable=False),
    sa.Column('holding_id', sa.Uuid(), nullable=True),
    sa.Column('identifier', sa.String(length=64), nullable=True),
    sa.Column('txn_type', sa.String(length=20), nullable=False),
    sa.Column('txn_date', sa.Date(), nullable=False),
    sa.Column('units', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('price', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('amount', sa.Numeric(precision=24, scale=2), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['holding_id'], ['holdings.id'], name=op.f('fk_transactions_holding_id_holdings'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_transactions_portfolio_id_portfolios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions'))
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_holding_id'), ['holding_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_identifier'), ['identifier'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_portfolio_id'), ['portfolio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_txn_date'), ['txn_date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_txn_date'))
        batch_op.drop_index(batch_op.f('ix_transactions_portfolio_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_identifier'))
        batch_op.drop_index(batch_op.f('ix_transactions_holding_id'))

    op.drop_table('transactions')
    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_uploaded_files_uploaded_by_id'))
        batch_op.drop_index(batch_op.f('ix_uploaded_files_portfolio_id'))

    op.drop_table('uploaded_files')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_deal_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_assignee_id'))

    op.drop_table('tasks')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_portfolio_id'))
        batch_op.drop_index(batch_op.f('ix_reports_generated_by_id'))

    op.drop_table('reports')
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notes_deal_id'))
        batch_op.drop_index(batch_op.f('ix_notes_client_id'))
        batch_op.drop_index(batch_op.f('ix_notes_author_id'))

    op.drop_table('notes')
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_holdings_portfolio_id'))
        batch_op.drop_index(batch_op.f('ix_holdings_identifier'))

    op.drop_table('holdings')
    with op.batch_alter_table('ai_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_reports_deal_id'))
        batch_op.drop_index(batch_op.f('ix_ai_reports_created_by_id'))

    op.drop_table('ai_reports')
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activities_deal_id'))
        batch_op.drop_index(batch_op.f('ix_activities_actor_id'))

    op.drop_table('activities')
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolios_client_id'))
        batch_op.drop_index(batch_op.f('ix_portfolios_benchmark_id'))

    op.drop_table('portfolios')
    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deals_stage'))
        batch_op.drop_index(batch_op.f('ix_deals_owner_id'))
        batch_op.drop_index(batch_op.f('ix_deals_name'))
        batch_op.drop_index(batch_op.f('ix_deals_company_id'))
        batch_op.drop_index(batch_op.f('ix_deals_client_id'))

    op.drop_table('deals')
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clients_relationship_manager_id'))
        batch_op.drop_index(batch_op.f('ix_clients_name'))
        batch_op.drop_index(batch_op.f('ix_clients_code'))

    op.drop_table('clients')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_name'))

    op.drop_table('roles')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_sector'))
        batch_op.drop_index(batch_op.f('ix_companies_name'))

    op.drop_table('companies')
    op.drop_table('benchmarks')
    # ### end Alembic commands ###
